/control/verbose 0

/control/execute quiet.mac

/run/numberOfThreads 1

/run/initialize

/vis/open OGL
/vis/drawVolume

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 2
/vis/scene/add/axes 0 0 0 50. cm
/vis/scene/endOfEventAction accumulate

/control/execute beam.mac